### ISSUE TITLE
history 기능 및 README.md 사용

### ISSUE THREAD

**Issue by 2dongyeop** [Yu-Jaeyoung/Java_working#3]
현재 코드에는 사용되지 않는 코드(향상된 for문을 사용하지 않는 조회, while문을 사용한 메인 메소드 등등)들이 주석으로 처리되어 있는데,
코드를 수정한 과정은 history 기능을 통해 이전 코드를 볼 수 있으니 지워도 됩니다.

또한, README.md에는 수정 사항을 기록하는 것은 괜찮으나, 이게 어떤 프로젝트인지 설명해주는 것이 좋습니다.

**Comment by Yu-Jaeyoung** [comment]
수정/반영하였습니다.
